Sc 56/test script for contracts
connie-ho/beginner-blocs pull request #11
Opened 2022-01-24 02:14 UTC by akshay-rakheja

Sample test script for contracts. Need to edit as per methods in market.sol.

2022-01-24 03:37 UTC, Justin1002 approved these changes

2022-01-24 03:43 UTC, connie-ho commented on test/sample-test.js
> +  })
maybe im missing something but should there be an expect statement for tis test?

2022-01-26 09:41 UTC, akshay-rakheja commented on test/sample-test.js
> +  })
Not sure yet but I think it's not required here

2022-01-26 17:22 UTC, connie-ho requested changes

2022-01-26 17:22 UTC, connie-ho commented on test/sample-test.js
> +  })
```suggestion
  })
  
  expect(items).to.deep.equal([{
    price: 1,
    //... other fields
  }, {
    price: 2,
    //... other fields in the item object to assert
  }])
```

2022-02-15 23:20 UTC, connie-ho commented
merge conflicts ):

2022-02-20 20:02 UTC, closed without merging