Sc 60/create nft page
connie-ho/beginner-blocs pull request #19
Opened 2022-02-13 02:40 UTC by akshay-rakheja

added pinata.js -> helps with pinning data to ipfs.

2022-02-13 19:49 UTC, connie-ho commented on scripts/interact.js
> +        <span>
Is this page suppose to be returning a react component? Where is this script used?

2022-02-13 21:16 UTC, connie-ho commented on scripts/minter.js
> +import { useEffect, useState } from "react";
Should make a component called Minter.jsx

2022-02-13 21:17 UTC, connie-ho commented on scripts/interact.js
> +import { pinJSONToIPFS } from "./pinata.js";
Move this to hooks/use-interact.js

2022-02-13 21:17 UTC, connie-ho commented on scripts/pinata.js
> +require('dotenv').config();
usePinata

2022-02-13 21:20 UTC, connie-ho requested changes
move to react app folder

2022-02-15 23:17 UTC, connie-ho commented on frontend/src/components/minter.jsx
> +  function addWalletListener() {
These functions could be extracted into a helper hook to clean up the component. It'll also help with testing (you can follow use-wallet-connection) as an example

2022-02-15 23:17 UTC, connie-ho commented on frontend/src/hooks/use-interact.js
> +const contractAddress = "0x4C4a07F737Bf57F6632B6CAB089B78f62385aCaE"; // need to change it to our contract address
You can import this directly from the config folder

2022-02-15 23:17 UTC, connie-ho commented on frontend/src/components/minter.jsx
> +import { useEffect, useState } from "react";
small nit! Component files should be capitalized

2022-02-15 23:17 UTC, connie-ho commented on frontend/src/components/minter.jsx
> +    <div className="Minter">
Please use styled components or useStyles when possible plspsspslps <3

2022-02-15 23:17 UTC, connie-ho commented on frontend/src/hooks/use-wallet-connection.js
> +    const provider = new ethers.getDefaultProvider('ropsten'); //saw this implementation here:  https://docs.ethers.io/v4/api-providers.html -> not sure but this seems like the recommended way to do
This is really good!!!! I think we can even change the ethers context with this now, but I can take this as a follow up

2022-02-16 07:32 UTC, akshay-rakheja commented on frontend/src/hooks/use-interact.js
> +const contractAddress = "0x4C4a07F737Bf57F6632B6CAB089B78f62385aCaE"; // need to change it to our contract address
thanks was looking for this.

2022-02-16 10:13 UTC, akshay-rakheja commented on scripts/pinata.js
> +require('dotenv').config();
done

2022-02-16 10:13 UTC, akshay-rakheja commented on frontend/src/components/minter.jsx
> +  function addWalletListener() {
tried doing it. can you guys please check if its done right??

2022-02-16 10:13 UTC, akshay-rakheja commented on frontend/src/components/minter.jsx
> +import { useEffect, useState } from "react";
done

2022-02-16 10:14 UTC, akshay-rakheja commented on frontend/src/components/minter.jsx
> +    <div className="Minter">
lol not sure what this is. will need your guys' help

2022-02-18 15:17 UTC, connie-ho commented
good job with the hook! Just need to fix those build (linting) errors and a few other suggestions and you are good to merge ::::::::))))))

2022-02-18 15:17 UTC, connie-ho requested changes

2022-02-18 15:18 UTC, connie-ho commented on frontend/src/components/minter.jsx
> +  function addWalletListener() {
good job it looks pretty good to me!

2022-02-27 22:55 UTC, closed without merging